import type { SkillNodeDefinition } from './skill-tree';

const ICONS: Record<string, string> = {
  'harvesting-bare-hands': 'hand.svg',
  'harvesting-strike-power': 'strength.png',
  'harvesting-precision': 'flint.png',
  'harvesting-critical-breaks': 'flint_and_steel.png',
  'harvesting-resource-yield': 'gold_nugget.png',
  'harvesting-combo-momentum': 'clock_00.png',
  'harvesting-multi-block': 'target_top.png',
  'harvesting-chain-mining': 'chain.png',
  'harvesting-mastery': 'enchanted_book.png',

  'tools-tool-bench': 'crafting_table_side.png',
  'tools-wooden-shovel': 'wooden_shovel.png',
  'tools-wooden-pickaxe': 'wooden_pickaxe.png',
  'tools-wooden-axe': 'wooden_axe.png',
  'tools-stone-set': 'stone_pickaxe.png',
  'tools-iron-shovel': 'iron_shovel.png',
  'tools-iron-pickaxe': 'iron_pickaxe.png',
  'tools-iron-axe': 'iron_axe.png',
  'tools-hoe-farming': 'wooden_hoe.png',
  'tools-shears': 'shears.png',
  'tools-bucket': 'bucket.png',
  'tools-diamond-set': 'diamond_pickaxe.png',
  'tools-reinforced': 'smithing_table_side.png',
  'tools-durability': 'anvil.png',
  'tools-mastery': 'enchanted_book.png',
  'tools-advanced-workshop': 'smithing_table_side.png',

  'materials-dirt-grass': 'dirt.png',
  'materials-stone': 'cobblestone.png',
  'materials-sand': 'sand.png',
  'materials-gravel': 'gravel.png',
  'materials-clay': 'clay_ball.png',
  'materials-logs-planks': 'oak_log.png',
  'materials-leaves-vines': 'oak_leaves.png',
  'materials-coal': 'coal.png',
  'materials-copper': 'copper_ingot.png',
  'materials-iron': 'iron_ingot.png',
  'materials-lapis': 'lapis_lazuli.png',
  'materials-redstone': 'redstone.png',
  'materials-gold': 'gold_ingot.png',
  'materials-diamond': 'diamond.png',
  'materials-emerald': 'emerald.png',
  'materials-obsidian': 'obsidian.png',
  'materials-deep-layer': 'deepslate.png',
  'materials-rare-ore-veins': 'diamond_ore.png',
  'materials-bedrock-boundary': 'bedrock.png',

  'automation-auto-strike': 'clock_00.png',
  'automation-mine-carts': 'minecart.png',
  'automation-chest-minecart': 'chest_minecart.png',
  'automation-redstone-rails': 'rail.png',
  'automation-target-queue': 'compass_00.png',
  'automation-block-priority': 'target_top.png',
  'automation-tool-selection': 'iron_pickaxe.png',
  'automation-miner-helper': 'villager.svg',
  'automation-second-worker': 'villager.svg',
  'automation-offline-efficiency': 'clock_00.png',
  'automation-tool-assignment': 'name_tag.png',
  'automation-storage-chest': 'chest_minecart.png',
  'automation-workshop-production': 'crafting_table_side.png',
  'automation-quarry': 'minecart.png',
  'automation-resource-conveyor': 'rail.png',
  'automation-mastery': 'enchanted_book.png',

  'world-adjacent-block': 'grass_block_top.png',
  'world-surface-3x3': 'grass_block_top.png',
  'world-underground-layer': 'deepslate.png',
  'world-cave-entrance': 'minecart.png',
  'world-water-tile': 'water_bucket.png',
  'world-forest-patch': 'oak_sapling.png',
  'world-desert-patch': 'sand.png',
  'world-mountain-patch': 'cobblestone.png',
  'world-snow-biome': 'snowball.png',
  'world-swamp-biome': 'vine.png',
  'world-crystal-biome': 'amethyst_shard.png',
  'world-biome-mixing': 'grass_block_top.png',
  'world-radius': 'map.png',
  'world-core': 'beacon.png',

  'life-saplings': 'oak_sapling.png',
  'life-crops': 'wheat_seeds.png',
  'life-farmland': 'farmland.png',
  'life-animals': 'animal.svg',
  'life-animal-pens': 'lead.png',
  'life-storage-shed': 'chest_minecart.png',
  'life-first-villager': 'villager.svg',
  'life-farmhouse': 'oak_door_bottom.png',
  'life-specialist-miner': 'iron_pickaxe.png',
  'life-specialist-farmer': 'wheat.png',
  'life-toolsmith': 'anvil.png',
  'life-trading': 'emerald.png',
  'life-settlement-paths': 'dirt_path_top.png',
  'life-villager-housing': 'oak_planks.png',
  'life-settlement-hub': 'bell.png',
  'life-living-world': 'villager.svg',

  'mastery-expanded-inventory': 'chest_minecart.png',
  'mastery-resource-ledger': 'book.png',
  'mastery-blueprint-system': 'map.png',
  'mastery-recipe-discovery': 'knowledge_book.png',
  'mastery-crafting-queue': 'hopper.png',
  'mastery-tool-infusions': 'enchanted_book.png',
  'mastery-mining-charms': 'totem_of_undying.png',
  'mastery-cosmetic-skins': 'white_dye.png',
  'mastery-world-challenges': 'target_top.png',
  'mastery-rare-events': 'clock_00.png',
  'mastery-seed-bonuses': 'oak_sapling.png',
  'mastery-prestige': 'nether_star.png',
  'mastery-new-game-plus': 'end_crystal.png',
};

export function getSkillNodeIconName(node: SkillNodeDefinition): string {
  return ICONS[node.id] ?? 'knowledge_book.png';
}
